### ISSUE TITLE
Problem with v7

### ISSUE THREAD

**Issue by simonsolutions** [drinks-it/pixi-api#3]
After upgrade from v6 to v7 I get the following error with the exact same code and every api function call.

> Attempted to call an undefined method named "getResultset" of class "stdClass".

The API call returns the following error behind:

> @param0" is not a parameter for procedure "pixiReport_StockValue", or it was supplied out of order.

It looks like it has to do with the changes in the function in line:

https://github.com/drinks-it/pixi-api/blob/2fe80f580c4cc348f7ea661094e013e72c2c2b3c/src/Pixi/API/Soap/Client.php#L86

**Comment by maximgubar** [comment]
@olegtytarenko could you please take a look?

**Comment by olegtytarenko** [comment]
@maximgubar 

Please review
